const BlogData = [
  {
    id: 1,
    date: "Yanvar 01, 2024",
    catgeory: "Biznes ",
    title: "Eng ashaddiy biznes-reja",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 2,
    date: "15 yanvar, 2023",
    catgeory: "Sayohat",
    title: "Chiroyli uy sahifasi",
    cover: "/images/singlepage/blog-2.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 3,
    date: "Yanvar 21, 2018",
    catgeory: "Rivojlanish",
    title: "Zamonaviy dizayn tushunchasi",
    cover: "/images/singlepage/blog-3.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 4,
    date: "Yanvar 30, 2019",
    catgeory: " Moushin dizayneri",
    title: "Smart moslashuvchan tashrif kartasi",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 5,
    date: "Yanvar 10, 2022",
    catgeory: "Kontent yozuvchi",
    title: "Investitsiyalarni rejalashtirish",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 6,
    date: "Yanvar 18, 2021",
    catgeory: "Veb-reja",
    title: "Nega har doim birinchi bo'lish kerak",
    cover: "/images/singlepage/blog-6.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 6,
    date: "Yanvar 12, 2014",
    catgeory: "Biznes strategiyasi",
    title: "Smart moslashuvchan tashrif kartasi",
    cover: "/images/singlepage/blog-1.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 7,
    date: "Yanvar 30, 2019",
    catgeory: " Moushin dizayneri",
    title: "Smart moslashuvchan tashrif kartasi",
    cover: "/images/singlepage/blog-4.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
  {
    id: 8,
    date: "January 10, 2022",
    catgeory: "Kontent yozuvchi",
    title: "Investitsiyalarni rejalashtirish",
    cover: "/images/singlepage/blog-5.jpg",
    para: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum.",
    desc: "Lorem ipsum dolor sit amet consectetur ipiscing elit amet consectetur piscing elit consectetur adipiscing elit sed et eletum. orem ipsum dolor sit amet consectetur adipiscing elit amet consectetur piscing elit amet consectetur adipiscing elit sed et eletum nulla eu placerat felis etiam tincidunt orci lacus id varius dolor fermum sit amet.",
  },
]

export default BlogData
